export type TranslationKey = 
  | 'title'
  | 'subtitle'
  | 'generator'
  | 'improvement'
  | 'advanced'
  | 'library'
  | 'categories'
  | 'integration'
  | 'advancedAI'
  | 'noCode'
  | 'domain'
  | 'specialization'
  | 'description'
  | 'objective'
  | 'format'
  | 'tone'
  | 'length'
  | 'generate'
  | 'generating'
  | 'result'
  | 'copy'
  | 'missingInfo'
  | 'fillAllFields'
  | 'generationError'
  | 'generatedPrompt'
  | 'copiedSuccess'
  | 'promptCopiedClipboard'
  | 'readyForGeneration'
  | 'aiWillCreate'
  | 'generatedByAI'
  | 'aiGeneratedDesc'
  | 'improvementTitle'
  | 'improvementDesc'
  | 'originalPrompt'
  | 'originalPromptPlaceholder'
  | 'improvementObjective'
  | 'improvementObjectivePlaceholder'
  | 'improvePrompt'
  | 'improvingPrompt'
  | 'improvedPrompt'
  | 'improvedPromptDesc'
  | 'improvements'
  | 'improvementSuccess'
  | 'improvementSuccessDesc'
  | 'enterOriginalPrompt'
  | 'required'
  | 'optional'
  | 'french'
  | 'english'
  | 'arabic'
  | 'textGeneration'
  | 'textGenerationDesc'
  | 'blogPostGenerator'
  | 'imageCreation'
  | 'imageCreationDesc'
  | 'interactiveDialogue'
  | 'interactiveDialogueDesc'
  | 'customerSupportChatbot'
  | 'codeGeneration'
  | 'codeGenerationDesc'
  | 'reactComponentGenerator'
  | 'dataAnalysis'
  | 'dataAnalysisDesc'
  | 'creativeWriting'
  | 'creativeWritingDesc'
  | 'blue'
  | 'green'
  | 'purple'
  | 'orange'
  | 'red'
  | 'indigo'
  | 'validationError'
  | 'nameDescriptionRequired'
  | 'categoryCreated'
  | 'categoryUpdated'
  | 'categoryDeleted'
  | 'editCategory'
  | 'createNewCategory'
  | 'categoryName'
  | 'colorTheme'
  | 'categoryDescription'
  | 'exampleUseCases'
  | 'update'
  | 'create'
  | 'cancel'
  | 'addCategory'
  | 'stepObjectiveTitle'
  | 'stepObjectiveDesc'
  | 'stepContextTitle'
  | 'stepContextDesc'
  | 'stepConstraintsTitle'
  | 'stepConstraintsDesc'
  | 'stepOutputFormatTitle'
  | 'stepOutputFormatDesc'
  | 'stepReviewTitle'
  | 'stepReviewDesc'
  | 'advancedPromptGenerated'
  | 'advancedPromptGeneratedDesc'
  | 'tryAgainLater'
  | 'multiStepBuilder'
  | 'multiStepBuilderDesc'
  | 'progress'
  | 'step'
  | 'previous'
  | 'next'
  | 'generateAdvancedPrompt'
  | 'advancedPromptResult'
  | 'professional'
  | 'casual'
  | 'technical'
  | 'creative'
  | 'persuasive'
  | 'educational'
  | 'authoritative'
  | 'friendly'
  | 'brief'
  | 'concise'
  | 'detailed'
  | 'comprehensive'
  | 'extensive'
  | 'structuredReport'
  | 'bulletPoints'
  | 'narrative'
  | 'stepByStep'
  | 'qaFormat'
  | 'presentation'
  | 'analytical'
  | 'descriptive'
  | 'comparative'
  | 'argumentative'
  | 'instructional'
  | 'consultative'
  | 'beginner'
  | 'intermediate'
  | 'expert'
  | 'toneStyle'
  | 'selectTone'
  | 'approximateLength'
  | 'selectLength'
  | 'technicalLevel'
  | 'selectTechnicalLevel'
  | 'responseFormat'
  | 'selectFormat'
  | 'writingStyle'
  | 'selectStyle'
  | 'stepConstraintsTips'
  | 'tipConstraints1'
  | 'tipConstraints2'
  | 'tipConstraints3'
  | 'technology'
  | 'healthcare'
  | 'finance'
  | 'education'
  | 'marketing'
  | 'retail'
  | 'manufacturing'
  | 'consulting';

const translations: Record<string, Record<TranslationKey, string>> = {
  en: {
    title: 'Prompt Generator Lab',
    subtitle: 'Create professional prompts with AI',
    generator: 'Generator',
    improvement: 'Improvement',
    advanced: 'Advanced',
    library: 'Library',
    categories: 'Categories',
    integration: 'Integration',
    advancedAI: 'Advanced AI',
    noCode: 'No Code',
    domain: 'Domain',
    specialization: 'Specialization',
    description: 'Description',
    objective: 'Objective',
    format: 'Format',
    tone: 'Tone',
    length: 'Length',
    generate: 'Generate',
    generating: 'Generating...',
    result: 'Result',
    copy: 'Copy',
    missingInfo: 'Missing Information',
    fillAllFields: 'Please fill in all required fields',
    generationError: 'Generation Error',
    generatedPrompt: 'Generated Prompt',
    copiedSuccess: 'Copied Successfully',
    promptCopiedClipboard: 'Prompt copied to clipboard',
    readyForGeneration: 'Ready for Generation',
    aiWillCreate: 'AI will create your prompt',
    generatedByAI: 'Generated by AI',
    aiGeneratedDesc: 'Review and adjust as needed',
    improvementTitle: 'Prompt Improvement',
    improvementDesc: 'Enhance your existing prompts with AI',
    originalPrompt: 'Original Prompt',
    originalPromptPlaceholder: 'Enter your existing prompt here...',
    improvementObjective: 'Improvement Objective',
    improvementObjectivePlaceholder: 'What aspect would you like to improve?',
    improvePrompt: 'Improve Prompt',
    improvingPrompt: 'Improving...',
    improvedPrompt: 'Improved Prompt',
    improvedPromptDesc: 'Your optimized prompt',
    improvements: 'Improvements Made',
    improvementSuccess: 'Improvement Complete',
    improvementSuccessDesc: 'Your prompt has been optimized',
    enterOriginalPrompt: 'Please enter the original prompt',
    required: '(required)',
    optional: '(optional)',
    french: 'Français',
    english: 'English',
    arabic: 'العربية',
    textGeneration: 'Text Generation',
    textGenerationDesc: 'Create written content',
    blogPostGenerator: 'Blog Post Generator',
    imageCreation: 'Image Creation',
    imageCreationDesc: 'Generate visual content',
    interactiveDialogue: 'Interactive Dialogue',
    interactiveDialogueDesc: 'Create conversational AI',
    customerSupportChatbot: 'Customer Support Chatbot',
    codeGeneration: 'Code Generation',
    codeGenerationDesc: 'Generate programming code',
    reactComponentGenerator: 'React Component Generator',
    dataAnalysis: 'Data Analysis',
    dataAnalysisDesc: 'Analyze and interpret data',
    creativeWriting: 'Creative Writing',
    creativeWritingDesc: 'Creative content creation',
    blue: 'Blue',
    green: 'Green',
    purple: 'Purple',
    orange: 'Orange',
    red: 'Red',
    indigo: 'Indigo',
    validationError: 'Validation Error',
    nameDescriptionRequired: 'Name and description are required',
    categoryCreated: 'Category Created',
    categoryUpdated: 'Category Updated',
    categoryDeleted: 'Category Deleted',
    editCategory: 'Edit Category',
    createNewCategory: 'Create New Category',
    categoryName: 'Category Name',
    colorTheme: 'Color Theme',
    categoryDescription: 'Category Description',
    exampleUseCases: 'Example Use Cases',
    update: 'Update',
    create: 'Create',
    cancel: 'Cancel',
    addCategory: 'Add Category',
    stepObjectiveTitle: 'Step 1: Objective',
    stepObjectiveDesc: 'Define the main goal',
    stepContextTitle: 'Step 2: Context',
    stepContextDesc: 'Provide background information',
    stepConstraintsTitle: 'Step 3: Constraints',
    stepConstraintsDesc: 'Set limitations and rules',
    stepOutputFormatTitle: 'Step 4: Output Format',
    stepOutputFormatDesc: 'Define the expected output',
    stepReviewTitle: 'Step 5: Review',
    stepReviewDesc: 'Review and generate',
    advancedPromptGenerated: 'Advanced Prompt Generated',
    advancedPromptGeneratedDesc: 'Your multi-step prompt is ready',
    tryAgainLater: 'Please try again later',
    multiStepBuilder: 'Multi-Step Builder',
    multiStepBuilderDesc: 'Create complex prompts step by step',
    progress: 'Progress',
    step: 'Step',
    previous: 'Previous',
    next: 'Next',
    generateAdvancedPrompt: 'Generate Advanced Prompt',
    advancedPromptResult: 'Advanced Prompt Result',
    professional: 'Professional',
    casual: 'Casual',
    technical: 'Technical',
    creative: 'Creative',
    persuasive: 'Persuasive',
    educational: 'Educational',
    authoritative: 'Authoritative',
    friendly: 'Friendly',
    brief: 'Brief',
    concise: 'Concise',
    detailed: 'Detailed',
    comprehensive: 'Comprehensive',
    extensive: 'Extensive',
    structuredReport: 'Structured Report',
    bulletPoints: 'Bullet Points',
    narrative: 'Narrative',
    stepByStep: 'Step by Step',
    qaFormat: 'Q&A Format',
    presentation: 'Presentation',
    analytical: 'Analytical',
    descriptive: 'Descriptive',
    comparative: 'Comparative',
    argumentative: 'Argumentative',
    instructional: 'Instructional',
    consultative: 'Consultative',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    expert: 'Expert',
    toneStyle: 'Tone & Style',
    selectTone: 'Select tone',
    approximateLength: 'Approximate Length',
    selectLength: 'Select length',
    technicalLevel: 'Technical Level',
    selectTechnicalLevel: 'Select technical level',
    responseFormat: 'Response Format',
    selectFormat: 'Select format',
    writingStyle: 'Writing Style',
    selectStyle: 'Select style',
    stepConstraintsTips: 'Step Constraints Tips',
    tipConstraints1: 'Define clear constraints for better results',
    tipConstraints2: 'Consider your target audience',
    tipConstraints3: 'Specify the desired output format',
    technology: 'Technology',
    healthcare: 'Healthcare',
    finance: 'Finance',
    education: 'Education',
    marketing: 'Marketing',
    retail: 'Retail',
    manufacturing: 'Manufacturing',
    consulting: 'Consulting'
  },
  fr: {
    title: 'Laboratoire de Génération de Prompts',
    subtitle: 'Créez des prompts professionnels avec l\'IA',
    generator: 'Générateur',
    improvement: 'Amélioration',
    advanced: 'Avancé',
    library: 'Bibliothèque',
    categories: 'Catégories',
    integration: 'Intégration',
    advancedAI: 'IA Avancée',
    noCode: 'Sans Code',
    domain: 'Domaine',
    specialization: 'Spécialisation',
    description: 'Description',
    objective: 'Objectif',
    format: 'Format',
    tone: 'Ton',
    length: 'Longueur',
    generate: 'Générer',
    generating: 'Génération...',
    result: 'Résultat',
    copy: 'Copier',
    missingInfo: 'Information Manquante',
    fillAllFields: 'Veuillez remplir tous les champs requis',
    generationError: 'Erreur de Génération',
    generatedPrompt: 'Prompt Généré',
    copiedSuccess: 'Copié avec Succès',
    promptCopiedClipboard: 'Prompt copié dans le presse-papiers',
    readyForGeneration: 'Prêt pour la Génération',
    aiWillCreate: 'L\'IA va créer votre prompt',
    generatedByAI: 'Généré par IA',
    aiGeneratedDesc: 'Vérifiez et ajustez si nécessaire',
    improvementTitle: 'Amélioration de Prompt',
    improvementDesc: 'Améliorez vos prompts existants avec l\'IA',
    originalPrompt: 'Prompt Original',
    originalPromptPlaceholder: 'Entrez votre prompt existant ici...',
    improvementObjective: 'Objectif d\'Amélioration',
    improvementObjectivePlaceholder: 'Quel aspect souhaitez-vous améliorer ?',
    improvePrompt: 'Améliorer le Prompt',
    improvingPrompt: 'Amélioration...',
    improvedPrompt: 'Prompt Amélioré',
    improvedPromptDesc: 'Votre prompt optimisé',
    improvements: 'Améliorations Apportées',
    improvementSuccess: 'Amélioration Terminée',
    improvementSuccessDesc: 'Votre prompt a été optimisé',
    enterOriginalPrompt: 'Veuillez entrer le prompt original',
    required: '(obligatoire)',
    optional: '(optionnel)',
    french: 'Français',
    english: 'English',
    arabic: 'العربية',
    textGeneration: 'Génération de Texte',
    textGenerationDesc: 'Créer du contenu écrit',
    blogPostGenerator: 'Générateur d\'Articles',
    imageCreation: 'Création d\'Images',
    imageCreationDesc: 'Générer du contenu visuel',
    interactiveDialogue: 'Dialogue Interactif',
    interactiveDialogueDesc: 'Créer une IA conversationnelle',
    customerSupportChatbot: 'Chatbot Support Client',
    codeGeneration: 'Génération de Code',
    codeGenerationDesc: 'Générer du code de programmation',
    reactComponentGenerator: 'Générateur de Composants React',
    dataAnalysis: 'Analyse de Données',
    dataAnalysisDesc: 'Analyser et interpréter les données',
    creativeWriting: 'Écriture Créative',
    creativeWritingDesc: 'Création de contenu créatif',
    blue: 'Bleu',
    green: 'Vert',
    purple: 'Violet',
    orange: 'Orange',
    red: 'Rouge',
    indigo: 'Indigo',
    validationError: 'Erreur de Validation',
    nameDescriptionRequired: 'Le nom et la description sont requis',
    categoryCreated: 'Catégorie Créée',
    categoryUpdated: 'Catégorie Mise à Jour',
    categoryDeleted: 'Catégorie Supprimée',
    editCategory: 'Modifier la Catégorie',
    createNewCategory: 'Créer une Nouvelle Catégorie',
    categoryName: 'Nom de la Catégorie',
    colorTheme: 'Thème Couleur',
    categoryDescription: 'Description de la Catégorie',
    exampleUseCases: 'Exemples d\'Utilisation',
    update: 'Mettre à jour',
    create: 'Créer',
    cancel: 'Annuler',
    addCategory: 'Ajouter une Catégorie',
    stepObjectiveTitle: 'Étape 1 : Objectif',
    stepObjectiveDesc: 'Définir l\'objectif principal',
    stepContextTitle: 'Étape 2 : Contexte',
    stepContextDesc: 'Fournir des informations de contexte',
    stepConstraintsTitle: 'Étape 3 : Contraintes',
    stepConstraintsDesc: 'Définir les limitations et règles',
    stepOutputFormatTitle: 'Étape 4 : Format de Sortie',
    stepOutputFormatDesc: 'Définir le format de sortie attendu',
    stepReviewTitle: 'Étape 5 : Révision',
    stepReviewDesc: 'Réviser et générer',
    advancedPromptGenerated: 'Prompt Avancé Généré',
    advancedPromptGeneratedDesc: 'Votre prompt multi-étapes est prêt',
    tryAgainLater: 'Veuillez réessayer plus tard',
    multiStepBuilder: 'Constructeur Multi-Étapes',
    multiStepBuilderDesc: 'Créer des prompts complexes étape par étape',
    progress: 'Progression',
    step: 'Étape',
    previous: 'Précédent',
    next: 'Suivant',
    generateAdvancedPrompt: 'Générer un Prompt Avancé',
    advancedPromptResult: 'Résultat du Prompt Avancé',
    professional: 'Professionnel',
    casual: 'Décontracté',
    technical: 'Technique',
    creative: 'Créatif',
    persuasive: 'Persuasif',
    educational: 'Éducatif',
    authoritative: 'Autoritaire',
    friendly: 'Amical',
    brief: 'Bref',
    concise: 'Concis',
    detailed: 'Détaillé',
    comprehensive: 'Complet',
    extensive: 'Étendu',
    structuredReport: 'Rapport Structuré',
    bulletPoints: 'Points à Puces',
    narrative: 'Narratif',
    stepByStep: 'Étape par Étape',
    qaFormat: 'Format Q&R',
    presentation: 'Présentation',
    analytical: 'Analytique',
    descriptive: 'Descriptif',
    comparative: 'Comparatif',
    argumentative: 'Argumentatif',
    instructional: 'Instructionnel',
    consultative: 'Consultatif',
    beginner: 'Débutant',
    intermediate: 'Intermédiaire',
    expert: 'Expert',
    toneStyle: 'Ton et Style',
    selectTone: 'Sélectionner le ton',
    approximateLength: 'Longueur Approximative',
    selectLength: 'Sélectionner la longueur',
    technicalLevel: 'Niveau Technique',
    selectTechnicalLevel: 'Sélectionner le niveau technique',
    responseFormat: 'Format de Réponse',
    selectFormat: 'Sélectionner le format',
    writingStyle: 'Style d\'Écriture',
    selectStyle: 'Sélectionner le style',
    stepConstraintsTips: 'Conseils pour les Contraintes',
    tipConstraints1: 'Définir des contraintes claires pour de meilleurs résultats',
    tipConstraints2: 'Considérer votre public cible',
    tipConstraints3: 'Spécifier le format de sortie désiré',
    technology: 'Technologie',
    healthcare: 'Santé',
    finance: 'Finance',
    education: 'Éducation',
    marketing: 'Marketing',
    retail: 'Commerce de Détail',
    manufacturing: 'Fabrication',
    consulting: 'Conseil'
  }
};

export default translations;
