// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imnyrscmccfgxvthxxxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltbnlyc2NtY2NmZ3h2dGh4eHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzkwMDgsImV4cCI6MjA3MTExNTAwOH0.wwLnNL0SxUF0bOGr2ROEHX-YR0Y579H2BA5_6VR4Pyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});